# HTTP Server
server:
  port: 8888

spring:
  # Spring Cloud Config Server Repository
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JosePaterninaA/pokeapi-config-server
          clone-on-start: true
          strict-host-key-checking: false
          force-pull: true

  # Spring properties in case you use different profiles
  #profiles:
  # active: dev