server:
  port: 8083

spring:
  application:
    name: "pokedex-strategy"

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8010/eureka

feign:
  clients:
    type:
      url: "http://localhost:8081"
      resource: "/api/pokedex/type"
      name: "pokemon-type"
    info:
      url: "http://localhost:8082"
      resource: "/api/pokedex/info"
      name: "pokemon-info"